import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'path';
import fs from 'fs';
import { spawnSync } from 'child_process';

// MODQN ω-Handover S2 — dev-server static-file middleware that serves the
// current producer baseline replay bundle to the browser via
// `/modqn-bundles/<basename>/...`. The bundle is derived by the producer's own
// `modqn-export` command from its current baseline run; leo-beam-sim only
// serves the generated bytes read-only. See docs/modqn-omega-handover-sdd.md
// §9.3.
//
// Boundary: bundle bytes are immutable per CLAUDE.md §3. The middleware
// streams files read-only after producer export. It writes only to /tmp and
// never writes back into modqn-paper-reproduction.
const MODQN_BUNDLE_FS_PATH =
  '/tmp/leo-beam-sim/modqn-bundles/baseline-modqn-pilot02-rerun-2026-05-15-export';
const MODQN_BUNDLE_ROUTE_PREFIX = '/modqn-bundles/';
const MODQN_PRODUCER_REPO_PATH = '/home/u24/papers/modqn-paper-reproduction';
const MODQN_PRODUCER_BASELINE_RUN_PATH = path.join(
  MODQN_PRODUCER_REPO_PATH,
  'artifacts/baseline-modqn-pilot02-rerun-2026-05-15/run',
);
const MODQN_EXPORT_BIN = path.join(MODQN_PRODUCER_REPO_PATH, '.venv/bin/modqn-export');
const MODQN_REQUIRED_BUNDLE_SURFACES = [
  'manifest.json',
  'provenance-map.json',
  'timeline/step-trace.jsonl',
] as const;

function hasRequiredModqnBundleSurfaces(): boolean {
  return MODQN_REQUIRED_BUNDLE_SURFACES.every(relative => (
    fs.existsSync(path.join(MODQN_BUNDLE_FS_PATH, relative))
  ));
}

function ensureModqnBundleExport(): { ok: true } | { ok: false; message: string } {
  if (hasRequiredModqnBundleSurfaces()) return { ok: true };

  if (!fs.existsSync(MODQN_EXPORT_BIN)) {
    return {
      ok: false,
      message: `MODQN export command is missing: ${MODQN_EXPORT_BIN}`,
    };
  }
  if (!fs.existsSync(MODQN_PRODUCER_BASELINE_RUN_PATH)) {
    return {
      ok: false,
      message: `MODQN producer baseline run is missing: ${MODQN_PRODUCER_BASELINE_RUN_PATH}`,
    };
  }

  fs.mkdirSync(path.dirname(MODQN_BUNDLE_FS_PATH), { recursive: true });
  const result = spawnSync(
    MODQN_EXPORT_BIN,
    ['--input', MODQN_PRODUCER_BASELINE_RUN_PATH, '--output-dir', MODQN_BUNDLE_FS_PATH],
    {
      cwd: MODQN_PRODUCER_REPO_PATH,
      encoding: 'utf8',
      env: {
        ...process.env,
        MPLCONFIGDIR: process.env.MPLCONFIGDIR ?? '/tmp/modqn-mplconfig',
      },
    },
  );

  if (result.status !== 0) {
    const detail = [result.stderr, result.stdout].filter(Boolean).join('\n').trim();
    return {
      ok: false,
      message: `MODQN producer export failed with status ${result.status ?? 'unknown'}${detail ? `: ${detail}` : ''}`,
    };
  }

  if (!hasRequiredModqnBundleSurfaces()) {
    return {
      ok: false,
      message: `MODQN producer export completed but required surfaces are missing under ${MODQN_BUNDLE_FS_PATH}`,
    };
  }

  return { ok: true };
}

function modqnBundleStaticServer(): Plugin {
  return {
    name: 'leo-beam-sim:modqn-bundle-static-server',
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const url = req.url ?? '';
        if (url === '/showcase-artifacts/visual-showcase-v1.json') {
          const filePath = '/home/u24/papers/modqn-paper-reproduction/artifacts/phase-01h-mp5-visual-showcase-cli-smoke-2026-05-22/visual-showcase-v1.json';
          fs.stat(filePath, (err, stat) => {
            if (!err && stat.isFile()) {
              res.setHeader('Content-Type', 'application/json');
              res.setHeader('Cache-Control', 'no-store');
              res.setHeader('X-Showcase-Artifact-Source', 'producer-pinned');
              fs.createReadStream(filePath).pipe(res);
              return;
            }
            // The pinned producer artifact is absent in this checkout. Fall back
            // to the repo-local loader so `npm run dev` can still show the
            // artifact-replay dashboard/flowchart. The loader may resolve a REAL
            // external artifact (VISUAL_SHOWCASE_ARTIFACT_PATH) or the synthetic
            // validator fixture, so derive the FIX-1 honesty header from the
            // loader's resolved source instead of hardcoding it — otherwise the
            // header would lie about an env-provided / regenerated real artifact
            // and the consumer badge would wrongly call it synthetic. Only the
            // canonical pinned path earns 'producer-pinned'; any other operator
            // override is surfaced as a non-pinned external source (§3 says an
            // unvalidated external artifact must not silently pass as proof).
            server
              .ssrLoadModule('/scripts/visualShowcaseValidatorFixture.ts')
              .then(mod => {
                const { artifact, source } = (mod as {
                  loadValidatorVisualShowcaseArtifact: () => {
                    artifact: unknown;
                    source: { kind: 'external' | 'synthetic'; isPinnedTrigger: boolean };
                  };
                }).loadValidatorVisualShowcaseArtifact();
                const artifactSourceHeader =
                  source.kind === 'synthetic'
                    ? 'synthetic-fixture-fallback'
                    : source.isPinnedTrigger
                      ? 'producer-pinned'
                      : 'external-artifact-path';
                res.setHeader('Content-Type', 'application/json');
                res.setHeader('Cache-Control', 'no-store');
                res.setHeader('X-Showcase-Artifact-Source', artifactSourceHeader);
                res.end(JSON.stringify(artifact));
              })
              .catch((fallbackError: unknown) => {
                res.statusCode = 404;
                res.end(`Showcase artifact not found; synthetic fallback failed: ${String(fallbackError)}`);
              });
          });
          return;
        }

        if (!url.startsWith(MODQN_BUNDLE_ROUTE_PREFIX)) return next();
        const remainder = url.slice(MODQN_BUNDLE_ROUTE_PREFIX.length);
        const slash = remainder.indexOf('/');
        if (slash === -1) return next();
        const basename = remainder.slice(0, slash);
        const relative = remainder.slice(slash + 1).split('?')[0] ?? '';
        const expectedBasename = path.basename(MODQN_BUNDLE_FS_PATH);
        if (basename !== expectedBasename) {
          res.statusCode = 404;
          res.end(`Unknown MODQN bundle basename: ${basename}`);
          return;
        }
        if (relative.includes('..')) {
          res.statusCode = 400;
          res.end('Path traversal not allowed');
          return;
        }
        const availability = ensureModqnBundleExport();
        if (!availability.ok) {
          res.statusCode = 503;
          res.end(availability.message);
          return;
        }
        const filePath = path.join(MODQN_BUNDLE_FS_PATH, relative);
        fs.stat(filePath, (err, stat) => {
          if (err || !stat.isFile()) {
            res.statusCode = 404;
            res.end(`MODQN bundle surface not found: ${relative}`);
            return;
          }
          const contentType = relative.endsWith('.json')
            ? 'application/json'
            : relative.endsWith('.jsonl')
              ? 'application/x-ndjson'
              : 'application/octet-stream';
          res.setHeader('Content-Type', contentType);
          res.setHeader('Cache-Control', 'no-store');
          fs.createReadStream(filePath).pipe(res);
        });
      });
    },
  };
}

export default defineConfig({
  plugins: [react(), modqnBundleStaticServer()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  server: {
    host: '0.0.0.0',
    port: 3000,
    open: true,
  },
  build: {
    outDir: 'dist',
    sourcemap: true,
    chunkSizeWarningLimit: 900,
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (!id.includes('node_modules')) return undefined;
          if (id.includes('/react/') || id.includes('/react-dom/') || id.includes('/scheduler/')) {
            return 'vendor-react';
          }
          if (
            id.includes('/three/')
            || id.includes('/@react-three/fiber/')
            || id.includes('/@react-three/drei/')
          ) {
            return 'vendor-three';
          }
          return 'vendor';
        },
      },
    },
  },
});
