import type { LabSnapshot } from '../session/visualLabSession';
import type { VisualLabCanonicalSnapshot } from '../../prototype/visual-lab-g0/visualLabCanonicalSnapshotAdapter';
import type { VisualLabCanonicalTimeline } from '../../prototype/visual-lab-g0/visualLabCanonicalTimelineAdapter';
import type { VisualLabFigureProfile } from '../../prototype/visual-lab-g0/presentation/visualLabPresentationContract';

export const TEST_PROFILE: VisualLabFigureProfile = {
  profileId: 'writer-fixture',
  theme: 'light',
  locale: 'en',
  viewport: { width: 800, height: 600, devicePixelRatio: 1 },
  cameraPreset: 'global-overview',
  layerPreset: 'minimal',
};

const identity = {
  frameId: 'writer-frame',
  tleFrameId: 'writer-tle-frame',
  runId: 'writer-run',
  analysisRunId: 'writer-analysis-run',
  geometryRunId: 'writer-geometry-run',
  instantUtc: '2026-08-16T00:00:00.000Z',
  instantTaipei: '2026-08-16T08:00:00+08:00',
  tleEpochUtc: '2026-08-15T23:59:00.000Z',
  constellation: 'starlink' as const,
  archiveId: 'writer-archive',
  archiveDate: '2026-08-16',
  selectedSatelliteId: 'writer-serving',
  candidateSatelliteId: 'writer-candidate',
  selectedTlePath: '/writer.tle',
  sourceKind: 'ARCHIVED_TLE' as const,
  propagationModel: 'SGP4' as const,
    contractVersion: 'family-b-thesis-3.13-3.17-v1' as const,
};

const canonical: VisualLabCanonicalSnapshot = {
  schemaVersion: 'visual-lab-canonical-snapshot-v1',
  isMock: false,
  source: {
    frameId: identity.frameId,
    tleFrameId: identity.tleFrameId,
    instantUtc: identity.instantUtc,
    instantTaipei: identity.instantTaipei,
    tleEpochUtc: identity.tleEpochUtc,
    selectedSatelliteId: identity.selectedSatelliteId,
    constellation: identity.constellation,
    archiveId: identity.archiveId,
    archiveDate: identity.archiveDate,
    selectedTlePath: identity.selectedTlePath,
    sourceKind: identity.sourceKind,
    propagationModel: identity.propagationModel,
    contractVersion: identity.contractVersion,
  },
  timeline: {
    availability: 'unavailable',
    instantUtc: identity.instantUtc,
    anchorIndex: null,
    anchorCount: null,
    elapsedSec: null,
    durationSec: null,
    stepSec: null,
    servingSatelliteId: identity.selectedSatelliteId,
    candidateSatelliteId: identity.candidateSatelliteId,
    servingPassId: null,
    candidatePassId: null,
  },
  serving: {
    availability: 'available',
    satelliteId: identity.selectedSatelliteId,
    beamId: 0,
    userId: 'writer-ue',
    sinrLinear: 2,
    sinrDb: 3.0103,
    requestedPowerW: 1,
    actualPowerW: 1,
    throughputBps: 100,
    instantaneousEeBitsPerJ: 100,
    distanceKm: 600,
    elevationDeg: 30,
    reason: null,
  },
  candidate: {
    availability: 'unavailable',
    satelliteId: identity.candidateSatelliteId,
    beamId: null,
    userId: null,
    sinrLinear: null,
    sinrDb: null,
    requestedPowerW: null,
    actualPowerW: null,
    throughputBps: null,
    instantaneousEeBitsPerJ: null,
    distanceKm: null,
    elevationDeg: null,
    reason: 'no candidate',
  },
  deltaSinrDb: null,
  throughput: { servingRateBps: 100, candidateRateBps: null, totalRateBps: 100, cumulativeDeliveredBits: 100 },
  power: { servingActualPowerW: 1, candidateActualPowerW: null, systemPowerW: 2, cumulativeConsumedEnergyJ: 2 },
  ee: { instantaneousBitsPerJ: 50, cumulativeBitsPerJ: 50 },
  evaluation: {
    availability: 'available',
    source: 'homepage-canonical-evaluation',
    deliveredBits: 100,
    consumedEnergyJ: 2,
    energyEfficiencyBitsPerJ: 50,
    durationSec: 1,
  },
  handover: {
    availability: 'unavailable',
    state: null,
    event: null,
    offsetDb: null,
    tttSec: null,
    progressSec: null,
    ratio: null,
    cumulativeCount: null,
    reason: 'no trace',
    servingSatelliteId: identity.selectedSatelliteId,
    candidateSatelliteId: identity.candidateSatelliteId,
    deltaDb: null,
    eventFromSatelliteId: null,
    eventToSatelliteId: null,
  },
};

const timeline: VisualLabCanonicalTimeline | null = null;

export function createTestSnapshot(): LabSnapshot {
  const accepted = {
    identity,
    frameId: identity.frameId,
    tleFrameId: identity.tleFrameId,
    runId: identity.runId,
    analysisRunId: identity.analysisRunId,
    geometryRunId: identity.geometryRunId,
    instantUtc: identity.instantUtc,
    canonical,
    timeline,
    global: null,
    local: null,
    beamScheduleTrace: null,
    intraHandoverEvidence: null,
    runReady: true,
  };
  return {
    phase: 'ready',
    accepted,
    draft: {} as LabSnapshot['draft'],
    presentation: { theme: TEST_PROFILE.theme, locale: TEST_PROFILE.locale, experience: 'figure', view: 'earth', density: 'clean', focus: 'none' },
    scenePlan: null,
    results: {} as LabSnapshot['results'],
    energy: {} as LabSnapshot['energy'],
    comparison: {} as LabSnapshot['comparison'],
    capture: {} as LabSnapshot['capture'],
    computation: { status: 'complete', completedAnchors: 241, totalAnchors: 241, fraction: 1 },
    error: null,
    canonical,
    timeline,
    globalScene: null,
    localScene: null,
  };
}
