import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
const APP='http://localhost:3000', SHELL='.leo-app-shell', C='canvas[data-camera-position]';
const sleep=(ms)=>new Promise(r=>setTimeout(r,ms));
await mkdir('output/min',{recursive:true});
const b=await chromium.launch(); const p=await b.newPage({viewport:{width:1280,height:800}});
await p.goto(APP,{waitUntil:'domcontentloaded'}); await p.waitForSelector(SHELL,{timeout:40000}); await p.waitForSelector(C,{timeout:40000});
await p.waitForFunction(()=>Number(document.querySelector('canvas[data-camera-position]')?.getAttribute('data-rendered-ue-count')??'0')>0,undefined,{timeout:90000});
await sleep(5000); await p.screenshot({path:'output/min/sinr.png'});
await p.click('[data-testid="lane-experience-modqn-live-cell-preview"]'); await p.waitForSelector(`${SHELL}[data-scene-lane="modqn-live-cell-preview"]`,{timeout:40000});
await sleep(5000); await p.screenshot({path:'output/min/modqn.png'});
console.log('MIN SHOT DONE'); await b.close();
